name: CI

on: [push]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ocaml-variants.5.2.1+options
          
      - name: Run tests
        run: |
          opam install dune --yes
          opam install . --deps-only --yes
          eval $(opam env)
          opam list
          dune runtest